version: '3'

services: 
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: mysql:5.7
    ports: 
      - ${DB_PORT}:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  web:
    container_name: ${WEB_CONTAINER_NAME}
    image: s1t2dev/php:7.3
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
    ports:
      - ${HTTP_PORT}:80
      
volumes:
  db_data:
